services:
  ros2_gateway:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: ros2_topic_gateway
    network_mode: host
    restart: unless-stopped
    environment:
      ROS_DOMAIN_ID: "0"
      GATEWAY_DEBUG: "1"
      DISPLAY: "${DISPLAY}"
      QT_X11_NO_MITSHM: "1"
      LIBGL_ALWAYS_SOFTWARE: "1"
    volumes:
      - ../common:/gateway/common
      - ../ros2:/gateway/ros2
      - ../config:/gateway/config
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority:ro
